sudo: false
language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
install:
  - node --version
  - npm --version
  - npm install
script:
  - node --version
  - npm --version
  - npm test
after_success:
