build: off
version: '{build}'
environment:
  matrix:
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'
platform:
  - x86
  - x64
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
