init:
    - git config --global core.autocrlf input
build: off
environment:
  matrix:
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'
platform:
  - x86
  - x64
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
test_script:
  - npm test
after_test:
  - npm run bench
